---

# https://serversforhackers.com/setting-up-mailcatcher
- name: Install dependecies
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - gcc-c++
    - sqlite-devel
    - ruby-devel
    - redhat-lsb
    - rubygems

- name: Install mailcatcher
  gem: name=mailcatcher state=present user_install=no

- name: Set mailcatcher upstart
  template: src=mailcatcher.conf.j2 dest=/etc/init.d/mailcatcher.conf
